#! /bin/bash

#ensure service running/stopped

function_start () {
service $1 status > /dev/null
if [ $? -ne 0 ]
then
   echo "service not started, starting service"
   service $1 start
else
   echo "service already started"
fi
}

function_stop () {
service $1 status > /dev/null
if [ $? == "0"  ]
then
   #echo "service not stopped, stopping service"
   service $1 stop
"\e[1;31m This is red text \e[0m"
   echo -e "\e[1;31m Error: service $1 on $3 stopped, because tomcat on $2 is down \e[0m" >&2
   exit 1
else
   echo -e "\e[1;31m Error: service $1 on $3 wasnt started, because tomcat on $2 is down \e[0m" >&2
   exit 1
   #echo "service stopped already"
fi
}

if [ $2 == "start" ]
then
   function_start $1 $3 $4
elif [ $2 == "stop" ]
then
   function_stop $1 $3 $4
fi
